- MoppApp/MoppApp/ContainerDetailsViewController.m
- MoppApp/MoppApp/Localizations.h
- MoppApp/MoppApp/Localizations.m
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
Also update variable names to correspond to updated translations
> Minor wording and grammar fixes

- POC/Tactivo/iEstEidUtil.xcodeproj/project.pbxproj
- POC/Tactivo/iEstEidUtil.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- POC/Tactivo/iEstEidUtil.xcodeproj/project.xcworkspace/xcshareddata/iEstEidUtil.xccheckout
- POC/Tactivo/iEstEidUtil/AppDelegate.h
- POC/Tactivo/iEstEidUtil/AppDelegate.m
- POC/Tactivo/iEstEidUtil/CardInfoViewController.h
- POC/Tactivo/iEstEidUtil/CardInfoViewController.m
- POC/Tactivo/iEstEidUtil/CardLib.h
- POC/Tactivo/iEstEidUtil/CardLib.mm
- POC/Tactivo/iEstEidUtil/MasterViewController.h
- POC/Tactivo/iEstEidUtil/MasterViewController.m
- POC/Tactivo/iEstEidUtil/PBAccessory.h
- POC/Tactivo/iEstEidUtil/PINViewController.h
- POC/Tactivo/iEstEidUtil/PINViewController.m
- POC/Tactivo/iEstEidUtil/en.lproj/InfoPlist.strings
- POC/Tactivo/iEstEidUtil/en.lproj/MainStoryboard_iPad.storyboard
- POC/Tactivo/iEstEidUtil/en.lproj/MainStoryboard_iPhone.storyboard
- POC/Tactivo/iEstEidUtil/iEstEidUtil-Info.plist
- POC/Tactivo/iEstEidUtil/iEstEidUtil-Prefix.pch
- POC/Tactivo/iEstEidUtil/main.m
- POC/Tactivo/iEstEidUtil/winscard.h
- POC/Tactivo/iEstEidUtil/wintypes.h
> Tactivo prototype

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerElements.xib
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/Extensions/UIViewController+Additions.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/Menu.storyboard
- MoppApp/MoppApp/MenuViewController.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/Signing.storyboard
- MoppApp/MoppApp/SigningElements.xib
- MoppApp/MoppApp/SigningFileImportCell.swift
- MoppApp/MoppApp/SigningFileImportMissingCell.swift
- MoppApp/MoppApp/SigningViewController.swift
- MoppApp/MoppApp/Utils.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.m
Error handling for removing remaining data file from container;
Error handling for removing signature;
Added version label in menu;
Changed version to 2.0;
Changed build to 13;
> Error handling for opening ddoc container without internet connection;

- MoppApp/MoppApp/LandingViewController.swift
> * Changed default container file type to ASiC-E

- MoppApp/MoppApp/DefaultsHelper.swift
- MoppApp/MoppApp/LaunchScreen.xib
Changed default container type to BDOC
MOPPIOS-231
> * Changed bottom margin of logo in launch screen

- MoppApp/MoppApp/ContainerActions.swift
> * Fixed: nested container created from legacy container can't be created more than once

- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MyeIDInfoViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/MoppLib/MoppLibCertificate.mm
- MoppLib/MoppLib/PublicInterface/MoppLibCertData.h
> * Added E-resident value to card type in My eID info

- MoppApp/MoppApp/MyEid.storyboard
> * Fixed: blocked PIN message not shown completely in My eID tab

- MoppApp/MoppApp/MenuViewController.swift
> * Open links when choosing "Help" from menu

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Extensions/UIStoryBoard+Additions.swift
- MoppApp/MoppApp/Jailbreak.storyboard
- MoppApp/MoppApp/JailbreakViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MoppApp+Jailbreak.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> * Implemented device jailbroken check

- MoppApp/MoppApp/Info.plist
- MoppApp/shareExtension/Info.plist
> * App version changed to 2.0.1

- MoppApp/MoppApp/AppDelegate.swift
- MoppApp/MoppApp/Constants.swift
- MoppApp/MoppApp/MoppApp.swift
> * Fixed deprecated 'openUrl' app delegate event

- MoppApp/MoppApp/Container.storyboard
> changed view for addressee add button

- MoppApp/MoppApp/Container.storyboard
> Cannot see full addressee info

- MoppApp/MoppApp/MyeIDViewController.swift
> * Fixed My eID changing PIN codes crash

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/SigningActions.swift
> Container validation broken

- CryptoLib/CryptoLib/Decrypt.mm
- CryptoLib/CryptoLib/XmlParser/DdocParserDelegate.h
- CryptoLib/CryptoLib/XmlParser/DdocParserDelegate.m
- MoppApp/MoppApp/MyEid.storyboard
> Decryption often fails with multiple files

- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/et.lproj/Localizable.strings
- MoppLib/ru.lproj/Localizable.strings
> Update and unify translations for iOS rel 2.1

- MoppApp/MoppApp/LandingViewController.swift
> added USER_CANCEL translation capability

- MoppApp/MoppApp/MoppApp.swift
> without jailbreak device check

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/DefaultsHelper.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/Session.swift
- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppApp/Podfile.lock
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
>  * Force use of TS signatures and remove BDOC/ASICE choice from settings

- MoppLib/MoppLib/MoppLibSOAPManager.m
> * Force time-stamp signing profile for mID signing

- MoppApp/MoppApp/AddresseeActions.swift
- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/ContainerAddresseeCell.swift
- MoppApp/MoppApp/ContainerFoundAddresseeCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibConstants.h
- MoppLib/MoppLib/PublicInterface/MoppLibCryptoActions.m
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
> * Fixed displaying correct addressee eID type

- CryptoLib/CryptoLib/XmlParser/CdocParserDelegate.m
> * Fixed CryptoLib cdoc parsing

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Configuration.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/InitializationViewController.swift
- MoppApp/MoppApp/MoppApp+Jailbreak.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/SettingsConfiguration.swift
- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/Podfile.lock
- MoppApp/SetupConfiguration/Sources/main.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/MoppLibPrivateConstants.h
- MoppLib/MoppLib/MoppLibPrivateConstants.m
- MoppLib/MoppLibNetworkManager.m
* MOPPIOS-651 - Dynamic TSL url
> MOPPIOS-651 - Dynamic TSL url

- MoppApp/MoppApp/ContainerSignatureCell.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibSignature.h
* MOPPIOS-707 - Google Drive-st .asice faili avamine ebaõnnestub
* MOPPIOS-565 - [Test environment] Test signatures missing "test" notation
> MOPPIOS-707, MOPPIOS-565

- MoppApp/MoppApp/ContainerSignatureCell.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibSignature.h
> Revert "MOPPIOS-707, MOPPIOS-565"

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/LOTLDecoder.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/TSLDownloader.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
> Re-download TSL after app update

- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/MoppApp.swift
> Container naming fix

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/AboutContent/licenses.html
- MoppApp/MoppApp/MimeTypeDecoder.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/Podfile
- MoppApp/Podfile.lock
> Fixed opening containers from Google Drive

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/InitializationViewController.swift
- MoppApp/MoppApp/SettingsConfiguration.swift
- MoppApp/MoppApp/SettingsViewController.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> TSA URL from settings

- MoppApp/MoppApp/Info.plist
- MoppApp/TestEnvInfo.plist
- MoppApp/shareExtension/Info.plist
> Update version to 2.4.0

- MoppApp/MoppApp/MobileIDSignature.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
> Remove prepared signature when signing fails

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Show friendly name on Signature title

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/AppDelegate.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/Podfile
- MoppApp/Podfile.lock
MOPPIOS-773\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Upgrade to Firebase Crashlytics

- MoppApp/MoppApp/AboutViewController.swift
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/DataFilePreviewViewController.swift
- MoppApp/MoppApp/Settings.storyboard
MOPPIOS-742\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Migrate from UIWebView to WKWebView

- MoppLib/MoppLib/bR301/ReaderInterface.h
- MoppLib/MoppLib/bR301/winscard.h
- MoppLib/MoppLib/bR301/wintypes.h
> Fixed ID-Card crash

- MoppApp/MoppApp/Extensions/UIViewController+Additions.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/SmartIDChallengeViewController.swift
> Remove signature while signing on app close

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Smart-ID NonQSCD signature fix

- MoppApp/MoppApp/Constants.swift
- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/SessionStatus.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- SkSigningLib/SkSigningLib.xcodeproj/project.pbxproj
- SkSigningLib/SkSigningLib/Models/Session/Request/SessionStatusRequestParameters.swift
- SkSigningLib/SkSigningLib/Requests/RequestSession.swift
- SkSigningLib/SkSigningLib/Requests/SIDRequest.swift
- SkSigningLib/SkSigningLib/Utilities/Constants.swift
> Increase Mobile-ID polling interval to 5 seconds

- MoppApp/MoppApp/DateFormatter.swift
> Fix 12h and 24h time formats

- MoppApp/MoppApp/Utils.swift
> Fix opening app with different phone languages

- SkSigningLib/SkSigningLib/Models/MobileIDError.swift
- SkSigningLib/SkSigningLib/Requests/RequestSession.swift
- SkSigningLib/SkSigningLib/Requests/RequestSignature.swift
- SkSigningLib/SkSigningLib/Requests/SIDRequest.swift
- SkSigningLib/SkSigningLib/Supporting Files/en.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/et.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/ru.lproj/Localizable.strings
> Check UUID format for Mobile-ID and Smart-ID

- MoppApp/MoppApp/MobileIDSignature.swift
- SkSigningLib/SkSigningLib/Requests/RequestSignature.swift
> Country code error support

- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
- SkSigningLib/SkSigningLib/Models/MobileIDError.swift
- SkSigningLib/SkSigningLib/Supporting Files/en.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/et.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/ru.lproj/Localizable.strings
> OCSP invalid time slot error support

- MoppApp/MoppApp/SmartIDSignature.swift
- SkSigningLib/SkSigningLib/Models/MobileIDError.swift
- SkSigningLib/SkSigningLib/Supporting Files/en.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/et.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/ru.lproj/Localizable.strings
> Certificate revoked error display

- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsViewController.swift
> Remove mobile number and ID code from settings

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
> Disable signing capabilities for ddoc, asics and scs

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/TSLUpdater.swift
> Add LOTL version to Diagnostics

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/PreviewFileTapGestureRecognizer.swift
> Disable file preview opening behind action buttons

- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibSignature.h
> Fix signature removing

- MoppApp/MoppApp/MyeIDInfoViewController.swift
- MoppApp/MoppApp/MyeIDPinPukCell.swift
> Fixed accessibility text reading

- MoppApp/MoppApp/SettingsHeaderCell.swift
- MoppApp/MoppApp/TokenFlowSelectionViewController.swift
> Improved accessibility screen reader order

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerHeaderCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Change container name

- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Translation changes

- MoppApp/MoppApp/ContainerTableViewHeaderView.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MyEid.storyboard
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Better accessibility element names

- MoppApp/MoppApp/MyeIDInfoViewController.swift
> My eID accessibility improvements

- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Say control code with accessibility

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/TSLUpdater.swift
> EE TSL version in Diagnostics view

- MoppApp/MoppApp/Container.storyboard
> Prevent filename to overlap icon

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/ContainerRemovalActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Remove last file from container

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/shareExtension/Info.plist
> Open multiple files

- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- SkSigningLib/SkSigningLib/Requests/RequestSession.swift
> Too many requests display message fixes

- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/en.lproj/Localizable.strings
- MoppLib/et.lproj/Localizable.strings
- MoppLib/ru.lproj/Localizable.strings
> Changed Mobile-ID signing screen

- MoppApp/MoppApp/Extensions/UIViewController+Additions.swift
> Non-bold container share display message

- MoppApp/MoppApp/IdCardViewController.swift
> Improve ID-card accessibility

- MoppApp/MoppApp/ScreenDisguise.swift
> Unblur control code view

- MoppLib/MoppLib/CardReaderiR301.m
- MoppLib/MoppLib/PublicInterface/MoppLibCardReaderManager.m
> Support other ID-card reader variant

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/TSLUpdater.swift
- SkSigningLib/SkSigningLib/Utilities/ErrorLog.swift
> Fix logging crash

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/UrlSchemeHandler.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppApp/shareExtension/Info.plist
> URL scheme support

- MoppApp/MoppApp/Constants.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/ScreenDisguise.swift
> Prevent screen recording

- MoppApp/MoppApp/SettingsConfiguration.swift
- MoppApp/SetupConfiguration/Sources/main.swift
> Central Configuration update interval changes

- MoppApp/MoppApp/Configuration.swift
- MoppApp/MoppApp/SettingsConfiguration.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MOPPLibConfiguration.h
- MoppLib/MoppLib/PublicInterface/MOPPLibConfiguration.m
> Certificate pinning for SiVa

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/DefaultsHelper.swift
- MoppApp/MoppApp/Extensions/Date+Additions.swift
> DDOC status changes

- MoppApp/MoppApp/SmartIDSignature.swift
- SkSigningLib/SkSigningLib/Models/SigningError.swift
- SkSigningLib/SkSigningLib/Requests/SIDRequest.swift
- SkSigningLib/SkSigningLib/Supporting Files/en.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/et.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/ru.lproj/Localizable.strings
> Account not found and timeout same error message

- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/Utils.swift
> Restrict RTL characters

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
> Sign button fixes

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerSignatureCell.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibConstants.h
> Removed test signature type

- MoppApp/MoppApp/AboutContent/licenses.html
> Updated licenses

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/DefaultsHelper.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/MimeTypeDecoder.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
> Fixed opening external files

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Adoc file opening fixes

- MoppApp/MoppApp/Info.plist
> Container opening fixes

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/FileDownloader.swift
- MoppApp/MoppApp/Info.plist
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/UrlSchemeHandler.swift
> Fixed external file opening

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/LandingViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Forbid opening empty files

- MoppApp/MoppApp/MenuLanguageButtonView.swift
- MoppApp/MoppApp/MenuLanguageCell.swift
- MoppApp/MoppApp/RecentContainersNameCell.swift
- MoppApp/MoppApp/RecentContainersViewController.swift
- MoppApp/MoppApp/SigningTableViewHeaderView.swift
> Menu view accessibility improvements

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/CryptoActions.swift
- MoppApp/MoppApp/CryptoViewController.swift
> Crypto view accessibility improvements

- MoppApp/MoppApp/ContainerViewController.swift
> Remove warning for invalid signatures

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/Podfile
- MoppApp/Podfile.lock
> Updated SwiftyRSA to version 1.7.0

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/PreviewActions.swift
> Container renaming and file opening fixes

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/SivaUtil.swift
> PDF send to SiVa confirmation improvements

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Update version to 2.4.5

- MoppApp/MoppApp/ContainerViewController.swift
> Save files from unsignable containers

- MoppApp/MoppApp/SmartIDSignature.swift
> Smart-ID dialog earlier

- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/MoppApp/TokenFlowSelectionViewController.swift
- MoppApp/MoppApp/Utils.swift
> Signing and settings view landscape mode support

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/FileManager.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Show container opening error

- MoppApp/MoppApp/DateFormatter.swift
> Use date format based on device settings

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Save diagnostics information

- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Message for file removal error

- MoppApp/MoppApp/Container.storyboard
> Warnings status design fixes

- SkSigningLib/SkSigningLib/Models/SigningError.swift
- SkSigningLib/SkSigningLib/Requests/RequestSession.swift
- SkSigningLib/SkSigningLib/Requests/RequestSignature.swift
- SkSigningLib/SkSigningLib/Supporting Files/en.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/et.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/ru.lproj/Localizable.strings
> Mobile-ID and Smart-ID technical error message

- MoppApp/MoppApp/PreviewActions.swift
> Fixed showing SiVa warning twice

- MoppApp/MoppApp/AddresseeActions.swift
- MoppApp/MoppApp/Container.storyboard
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Fix displaying long names

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
> iOS 15 file adding fixes

- MoppApp/MoppApp/ContainerViewController.swift
> Fixed adding file to crypto containers

- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/SmartIDChallengeViewController.swift
- MoppApp/MoppApp/SmartIDEditViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Signing accessibility improvements

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Run initialization synchronously

- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Signing crash fix

- MoppApp/MoppApp/Configuration.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
> Remove MID-SIGN-URL configuration field

- MoppApp/Podfile
- MoppApp/Podfile.lock
> Updated OCMock to version 3.9.1

- MoppApp/MoppApp/ContainerAddresseeCell.swift
- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerFoundAddresseeCell.swift
- MoppApp/MoppApp/ContainerHeaderCell.swift
- MoppApp/MoppApp/ContainerImportAddressees.swift
- MoppApp/MoppApp/ContainerImportFilesCell.swift
- MoppApp/MoppApp/ContainerNoAddresseesCell.swift
- MoppApp/MoppApp/ContainerSignatureCell.swift
- MoppApp/MoppApp/ContainerTableViewHeaderView.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoViewController.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/MobileIDEditViewController.swift
- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/SigningViewController.swift
- MoppApp/MoppApp/SmartIDEditViewController.swift
- MoppApp/MoppApp/TokenFlowSelectionViewController.swift
> Accessibility text size improvements

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Fixed crypto addressee policy

- MoppApp/MoppApp/Container.storyboard
> Filename design fixes

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated version to 2.4.6

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated version to 2.4.7

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/DefaultsHelper.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsDefaultValueCell.swift
- MoppApp/MoppApp/SettingsFieldCell.swift
- MoppApp/MoppApp/SettingsTimeStampCell.swift
- MoppApp/MoppApp/SettingsViewController.swift
> Use one switch for both settings

- MoppApp/MoppApp/MobileIDEditViewController.swift
- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/SmartIDEditViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/MoppApp/TokenFlowUtil.swift
> Added errors to Smart-ID field

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/MoppApp/TokenFlowUtil.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Added errors to ID-card view

- MoppApp/MoppApp/AboutContent/licenses.html
> Remove horizontal scrolling in About view

- MoppApp/MoppApp/ContainerViewController.swift
- MoppLib/MoppLib/MoppLibCertificate.mm
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.m
> Container name change crash fix

- MoppApp/Podfile
- MoppApp/Podfile.lock
> Firebase updated to version 10.0.0

- MoppApp/MoppApp/ContainerActions.swift
> Fixed container not showing files

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp/SettingsFieldCell.swift
- MoppApp/MoppApp/SettingsHeaderCell.swift
- MoppApp/MoppApp/SettingsTimeStampCell.swift
- MoppApp/MoppApp/SettingsViewController.swift
> Settings accessibility improvements

- MoppApp/MoppApp/ContainerElements.xib
- MoppApp/MoppApp/TokenFlow.storyboard
> Accessibility texts as headers

- MoppApp/MoppApp/AboutViewController.swift
- MoppApp/MoppApp/CryptoViewController.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/RecentContainers.storyboard
- MoppApp/MoppApp/RecentContainersHeaderCell.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsHeaderCell.swift
- MoppApp/MoppApp/SigningViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Accessibility texts improvements

- MoppApp/MoppApp/Assets.xcassets/Colors/MoppContentLine.colorset/Contents.json
- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/MyeIDChangeCodeViewControllerUI.swift
> Changed textfields border color

- MoppApp/MoppApp/AboutContent/about_en.html
- MoppApp/MoppApp/AboutContent/about_et.html
- MoppApp/MoppApp/AboutContent/about_ru.html
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Accessible DigiDoc and EL icons

- MoppApp/Podfile
- MoppApp/Podfile.lock
> Updated ZipFoundation to version 0.9.15

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/TSLUpdater.swift
> Diagnostics view logging

- MoppApp/MoppApp/RecentContainersViewController.swift
> Fixed containers not appearing in recent documents

- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
> Fixed VoiceOver not working after signing with Mobile-ID

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/MobileIDEditViewController.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/SmartIDEditViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
> Move keyboard on textview click

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Configuration.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/FileUtil.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SmartIDSignature.swift
- MoppApp/MoppApp/Utils.swift
- SkSigningLib/SkSigningLib/Models/SigningError.swift
- SkSigningLib/SkSigningLib/Models/SmartID/Request/SIDSignatureRequestParameters.swift
- SkSigningLib/SkSigningLib/Models/SmartID/Response/SIDSessionStatusResponse.swift
- SkSigningLib/SkSigningLib/Requests/SIDRequest.swift
- SkSigningLib/SkSigningLib/Supporting Files/en.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/et.lproj/Localizable.strings
- SkSigningLib/SkSigningLib/Supporting Files/ru.lproj/Localizable.strings
> Smart-ID API v2

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated version to 2.5.0

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/Settings.storyboard
> Diagnostics saving improvements

- MoppApp/MoppApp/SmartIDEditViewController.swift
> Fixed Smart-ID remember me switch state

- MoppApp/MoppApp/SmartIDSignature.swift
> Smart-ID symbols fix

- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
> Bigger signing view modal

- MoppApp/MoppApp/TokenFlow.storyboard
> ID-card view improvements

- MoppApp/MoppApp/ContainerActions.swift
> Fixed not showing error opening faulty container

- MoppApp/MoppApp/AlertUtil.swift
- MoppApp/MoppApp/ErrorUtil.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/SigningActions.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/SmartIDChallengeViewController.swift
> Fixed ID-card error message

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Version updated to 2.6.0

- MoppApp/MoppApp/AddresseeViewController.swift
> Crypto recipient search improvements

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/AlertUtil.swift
- MoppApp/MoppApp/CancelUtil.swift
- MoppApp/MoppApp/Constants.swift
- MoppApp/MoppApp/FileUtil.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/SmartIDChallengeViewController.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- SkSigningLib/SkSigningLib.xcodeproj/project.pbxproj
- SkSigningLib/SkSigningLib/Models/SigningError.swift
- SkSigningLib/SkSigningLib/Requests/Mobile-ID/CancelRequest.swift
- SkSigningLib/SkSigningLib/Requests/Mobile-ID/RequestSession.swift
- SkSigningLib/SkSigningLib/Requests/Mobile-ID/RequestSignature.swift
- SkSigningLib/SkSigningLib/Requests/Smart-ID/SIDRequest.swift
- SkSigningLib/SkSigningLib/Utilities/CancelRequestUtil.swift
> Cancel Mobile-ID and Smart-ID signing

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/LandingViewController.swift
> Switched crypto buttons locations

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/DiagnosticError.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/Extensions/UIViewController+Additions.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/SettingsConfiguration.swift
> Added no internet connection message to configuration refreshing

- MoppApp/MoppApp/ContainerViewController.swift
> ASICS signature details fixes

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerHeaderCell.swift
- MoppApp/MoppApp/Extensions/CharacterSet+Additions.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/et.lproj/Localizable.strings
> Improved files support with symbols

- MoppApp/MoppApp/SettingsFieldCell.swift
> Placeholder text improvements

- MoppApp/MoppApp/Constants.swift
- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/ScaledButton.swift
- MoppApp/MoppApp/TokenFlow.storyboard
> Landscape ID-card accessibility fixes

- MoppApp/MoppApp/UrlSchemeHandler.swift
> Fixes for opening with protocol

- MoppApp/MoppApp/Settings.storyboard
> Diagnostics fonts adjustments

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/AlertUtil.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Improved crypto view personal code handling

- MoppApp/MoppApp/SmartIDEditViewController.swift
> Fixed Smart-ID keyboard

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/SigningActions.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
> Fixed container notifications when previewing files

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerAddAllButtonCell.swift
- MoppApp/MoppApp/ContainerFoundAddresseeCell.swift
- MoppApp/MoppApp/CryptoContainer.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/RecentContainersViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Add all recipients

- MoppApp/MoppApp/DataFilePreviewViewController.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
> Preview file encoding fixes

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoActions.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Better title for encrypted files

- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Text changes

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/FileUtil.swift
> Default container name when file name is empty

- .github/workflows/build.yml
> Added libdigidocpp artifact

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/DataFilePreviewViewController.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
> File preview improvements

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/ContainerAddAllButtonCell.swift
- MoppApp/MoppApp/ContainerFoundAddresseeCell.swift
> Hide crypto confirm button when no addressees

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/SearchField.swift
> Remove search results when searchfield is empty

- MoppApp/MoppApp/AddresseeViewController.swift
> Fixed addressee confirm button

- MoppApp/MoppApp/SmartIDEditViewController.swift
> Fixed Smart-ID personal code error accessibility

- MoppApp/MoppApp/FontUtil.swift
- MoppApp/MoppApp/ScaledButton.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsTSACertCell.swift
- MoppApp/MoppApp/SettingsViewController.swift
> Show TSA buttons when default switch is off

- MoppApp/MoppApp/TokenFlow.storyboard
> Fixed translations changing on transition

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
> FIxed crash when file name has emoji

- MoppApp/MoppApp/ContainerViewController.swift
> Fixed crash after signing

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> File preview fixes

- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/SmartIDChallengeViewController.swift
> Fixed signing cancelling crash

- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/SmartIDChallengeViewController.swift
> Fixed deinit not called on error notification

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> ASICS container validation fixes

- MoppApp/MoppApp/TokenFlowSelectionViewController.swift
> Hide signing tabs on decryption

- MoppApp/MoppApp/Container.storyboard
> Border design fixes

- MoppApp/MoppApp/MyEid.storyboard
- MoppApp/MoppApp/MyeIDStatusViewController.swift
> Added spinner to My eID loading view

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerHeaderCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
> Fixed save button flashing in nested container

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/TSLUpdater.swift
> Fixed showing TSL files in Diagnostics

- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
> Fixed double signatures in ASICS containers

- MoppApp/MoppApp/ContainerFileCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
> Fixed buttons in crypto view

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerSearchCell.swift
- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/SearchField.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/MoppApp/TokenFlowSelectionViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Improved ID-card view modal size

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/RecentContainers.storyboard
- MoppApp/MoppApp/RecentContainersNameCell.swift
- MoppApp/MoppApp/RecentContainersViewController.swift
> File name spacing changes

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/MoppApp/TokenFlowSelectionViewController.swift
> Signing design improvements

- MoppApp/MoppApp/IdCardViewController.swift
> Pin code field fixes

- CryptoLib/CryptoLib.xcodeproj/project.pbxproj
> Define LDAP_PATH variable and reuse and cleanup project options

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/AlertUtil.swift
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoActions.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/Extensions/String+Additions.swift
- MoppApp/MoppApp/Extensions/UIAlertAction+Additions.swift
- MoppApp/MoppApp/Extensions/UIViewController+Additions.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MobileIDChallengeViewController.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/MyeIDChangeCodesViewController.swift
- MoppApp/MoppApp/PreviewActions.swift
- MoppApp/MoppApp/SettingsTSACertCell.swift
- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/MoppApp/SigningActions.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/SivaUtil.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/MoppLib/PublicInterface/MoppLibCryptoActions.m
> Fixed LDAP Not Found message

- MoppApp/MoppApp/TokenFlow.storyboard
> Fixed Display Zoomed mode

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated app version to 2.6.1

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated app to version 2.7.0

- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Fixed file exists message

- MoppApp/MoppApp/Crypto.storyboard
- MoppApp/MoppApp/CryptoViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/MenuViewController.swift
- MoppApp/MoppApp/Signing.storyboard
- MoppApp/MoppApp/SigningViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Recent documents button to main screen

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated app version to 2.6.2

- MoppApp/MoppApp/AddresseeViewController.swift
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/LandingViewController.swift
- MoppApp/MoppApp/PreviewActions.swift
> Added encrypt button to signing view

- MoppApp/MoppApp/ContainerViewController.swift
> Forbid signing adoc containers

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SignatureDetailsViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Added timestamp details translation

- MoppApp/MoppApp/ContainerSignatureCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
> Fix getting role details

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/MobileIDEditViewController.swift
- MoppApp/MoppApp/PersonalCodeField.swift
- MoppApp/MoppApp/ScaledTextField.swift
- MoppApp/MoppApp/SmartIDEditViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
> Fixed allowing signing with invalid personal code

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerSignatureCell.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
> Improved role and address accessibility

- MoppApp/MoppApp/CertificateDetailViewController.swift
- MoppApp/MoppApp/MoppViewController.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsTSACertCell.swift
- MoppApp/MoppApp/SettingsViewController.swift
> Fixed hidden Settings certificate buttons

- MoppApp/MoppApp/ContainerViewController.swift
> Change container name on creation

- CryptoLib/CryptoLib/XmlParser/CdocParserDelegate.m
- MoppLib/MoppLib/CardActionsManager.m
- MoppLib/MoppLib/MoppLibCertificate.h
- MoppLib/MoppLib/MoppLibCertificate.mm
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibCryptoActions.m
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
> No need to convert certificate to PEM and DER

- MoppApp/MoppApp/Accessibility.storyboard
- MoppApp/MoppApp/AccessibilityViewController.swift
> Fix Accessibility view header traits

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp/Configuration.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- SkSigningLib/SkSigningLib/Requests/Smart-ID/SIDRequest.swift
> Removed Smart-ID v1 support

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/LandingViewController.swift
> Added sign button to crypto view

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated Firebase version to 10.18.0

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Updated ZIPFoundation version to 0.9.17

- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- MoppApp/MoppApp/Utils.swift
- SkSigningLib/SkSigningLib/Utilities/Logging.swift
> Fix logging to file in release mode

- MoppLib/MoppLib/MoppLibCertificate.mm
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibCertificateInfo.mm
- MoppLib/MoppLib/PublicInterface/MoppLibCryptoActions.m
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
> Fix some memory leaks

- MoppApp/MoppApp/RecentContainers.storyboard
- MoppApp/MoppApp/RecentContainersElements.xib
- MoppApp/MoppApp/RecentContainersHeaderCell.swift
- MoppApp/MoppApp/SearchTextField.swift
- MoppApp/MoppApp/SigningTableViewHeaderView.swift
> Improve Recent Containers header design

- MoppApp/MoppApp/CertificateDetailViewController.swift
- MoppApp/MoppApp/MoppViewController.swift
> Fix certificate detail back button

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Extensions/UIFont+Additions.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsResetCell.swift
- MoppApp/MoppApp/SettingsSivaCertCell.swift
- MoppApp/MoppApp/SettingsTSACertCell.swift
- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
> Reset Settings

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp.xcodeproj/project.pbxproj
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
> CodeQL support

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp.xcodeproj/project.pbxproj
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
> Fix Github Actions

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/MobileIDEditViewController.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsFieldCell.swift
- MoppApp/MoppApp/SettingsTimeStampCell.swift
- MoppApp/MoppApp/SmartIDEditViewController.swift
- MoppApp/MoppApp/TokenFlow.storyboard
> Add new color to textfield labels

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerNotificationCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Add message to ASICS containers

- MoppApp/MoppApp/Container.storyboard
> Fix LDAP search keyboard cache

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp/CertUtil.swift
- MoppApp/MoppApp/CertificateDetailViewController.swift
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoViewController.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/FileDownloader.swift
- MoppApp/MoppApp/FileLogUtil.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/RecentContainersViewController.swift
- MoppApp/MoppApp/SignatureDetailsViewController.swift
- MoppApp/MoppApp/UrlSchemeHandler.swift
- MoppLib/MoppLib/MLFileManager.h
- MoppLib/MoppLib/MLFileManager.m
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Move file handling from Documents to Library

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/KeychainUtil.swift
> Add more restrictive keychain usage

- MoppApp/MoppApp/Container.storyboard
> Fix edit container button keyboard navigation

- MoppApp/MoppApp/CryptoActions.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/CryptoViewController.swift
- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
> Remove files after use

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SignatureUtil.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/SivaUtil.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.h
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.m
> Show message in container with CAdES signatures

- MoppApp/MoppApp/AccessibilityViewController.swift
- MoppApp/MoppApp/Menu.storyboard
- MoppApp/MoppApp/MenuCell.swift
- MoppApp/MoppApp/MenuViewController.swift
- MoppApp/MoppApp/Utils.swift
> Fix Voice Control in Menu

- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsResetCell.swift
> Fix keyboard use in Settings

- MoppApp/MoppApp/CryptoActions.swift
- MoppApp/MoppApp/DefaultsHelper.swift
- MoppApp/MoppApp/Extensions/UIViewController+Additions.swift
- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Remove document share notification

- CryptoLib/CryptoLib.xcodeproj/project.pbxproj
- CryptoLib/CryptoLib/LDAPResponse.h
- CryptoLib/CryptoLib/LDAPResponse.m
- CryptoLib/CryptoLib/Ldap/OpenLdap.h
- CryptoLib/CryptoLib/Ldap/OpenLdap.m
- MoppApp/MoppApp/AddresseeViewController.swift
- MoppLib/MoppLib/PublicInterface/MoppLibCryptoActions.m
> Add support for LDAP certificate sets

- MoppApp/MoppApp/FileLogUtil.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/RoleAndAddressViewController.swift
- MoppApp/MoppApp/Utils.swift
- SkSigningLib/SkSigningLib/Utilities/Logging.swift
> Fix logging to file

- CryptoLib/CryptoLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- MoppApp/MoppApp/Accessibility.storyboard
- MoppApp/MoppApp/Menu.storyboard
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsHeaderCell.swift
- MoppApp/MoppApp/TokenFlow.storyboard
- MoppApp/shareExtension/shareExtension.entitlements
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
> Unify header designs

- MoppApp/MoppApp/AppInfoCell.swift
- MoppApp/MoppApp/LicensesCell.swift
> Fix link underline color

- MoppApp/MoppApp/ContainerActions.swift
> Fix opening PDF documents

- MoppApp/MoppApp/Container.storyboard
- MoppApp/MoppApp/ContainerHeaderCell.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
- MoppApp/MoppApp/SigningContainerViewController.swift
> Add save button to containers

- MoppApp/MoppApp/FileManager.swift
> Fix sending file to SiVa

- MoppApp/MoppApp/LocalizationKeys.swift
- MoppApp/MoppApp/Settings.storyboard
- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/MoppApp/en.lproj/Localizable.strings
- MoppApp/MoppApp/et.lproj/Localizable.strings
- MoppApp/MoppApp/ru.lproj/Localizable.strings
> Show reset settings done message

- MoppApp/MoppApp/ContainerActions.swift
> Fix cancelling DDOC and signed PDF opening

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/FileUtil.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/MoppApp/RecentContainersNameCell.swift
- MoppApp/MoppApp/Utils.swift
- SkSigningLib/SkSigningLib.xcodeproj/xcuserdata/martenr.xcuserdatad/xcschemes/xcschememanagement.plist
- SkSigningLib/SkSigningLib/Utilities/Logging.swift
> Fix CodeQL results

- MoppApp/MoppApp/ContainerActions.swift
- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/PreviewActions.swift
- MoppApp/MoppApp/RecentContainersViewController.swift
- MoppApp/MoppApp/SignatureUtil.swift
- MoppApp/MoppApp/SivaUtil.swift
> Fix Xades files handling

- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/AccessibilityViewController.swift
- MoppApp/MoppApp/EncryptedDataUtil.swift
- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/KeychainUtil.swift
- MoppApp/MoppApp/ManualProxy.swift
- MoppApp/MoppApp/NFCEditViewController.swift
- MoppApp/MoppApp/ProxyViewController.swift
> Encrypt CAN number when stored

- MoppApp/MoppApp/FileUtil.swift
- MoppApp/MoppApp/MimeTypeExtractor.swift
- MoppApp/MoppApp/MoppApp.swift
> Fix opening external files

- MoppApp/MoppApp/NFCEditViewController.swift
> Fix showing CAN text without NFC support

- MoppApp/MoppApp/CertificateDetailViewController.swift
> Fix back button in Certificate view

- MoppApp/MoppApp/FileManager.swift
- MoppApp/MoppApp/FileUtil.swift
- MoppApp/MoppApp/MoppApp.swift
- MoppApp/shareExtension/ShareViewController.m
- MoppApp/shareExtension/shareExtension.entitlements
> Fix opening multiple external files

- MoppApp/MoppApp.xcodeproj/project.pbxproj
> Update app version to 2.8.0

- MoppApp/MoppApp/NFCSignature.swift
> Fix adding role data with NFC

- MoppApp/MoppApp/DiagnosticsViewController.swift
- MoppApp/MoppApp/SettingsViewController.swift
- MoppApp/MoppApp/Signing/SivaCertViewController.swift
- MoppLib/MoppLib/MoppLibDigidocManager.mm
> Fix finding SiVa cert

- MoppApp/MoppApp/MobileIDSignature.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
- SkSigningLib/SkSigningLib/Utilities/ControlCode.swift
> Use NSData, no need to convert to NSArray

- CryptoLib/CryptoLib/Ldap/Addressee.h
- MoppApp/MoppApp/AddresseeViewController.swift
- MoppLib/MoppLib/MoppLibCertificate.mm
- MoppLib/MoppLib/PublicInterface/MoppLibCerificatetData.h
- MoppLib/MoppLib/PublicInterface/MoppLibCryptoActions.m
- MoppLib/MoppLib/PublicInterface/MoppLibManager.h
- MoppLib/MoppLib/PublicInterface/MoppLibManager.m
> Reuse code

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- MoppApp/MoppApp.xcodeproj/project.pbxproj
- MoppApp/MoppApp/Info.plist
- MoppApp/shareExtension/Info.plist
- SkSigningLib/SkSigningLib.xcodeproj/project.pbxproj
> Use XCode versioning

- MoppApp/MoppApp/ContainerViewController.swift
- MoppApp/MoppApp/CryptoContainerViewController.swift
> Fix opening CDOC data files

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/NFCSignature.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.h
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.mm
- MoppLib/MoppLib/PublicInterface/MoppLibManager.swift
MOPPAND-1515
Set NFC true in User-Agent for NFC signing.
Signed-off-by: Boriss Melikjan <boriss.melikjan@nortal.com>
> Set NFC true in User-Agent for NFC signing.

- MoppApp/MoppApp/IdCardViewController.swift
- MoppApp/MoppApp/MobileIDSignature.swift
- MoppApp/MoppApp/NFCSignature.swift
- MoppApp/MoppApp/SmartIDSignature.swift
- MoppLib/MoppLib/MoppLibDigidocManager.h
- MoppLib/MoppLib/MoppLibDigidocManager.mm
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.h
- MoppLib/MoppLib/PublicInterface/MoppLibContainerActions.mm
- MoppLib/MoppLib/PublicInterface/MoppLibManager.swift
> Show external devices in User-Agent only with ID-card signing

- codemagic.yaml
> Update test configuration URL

- MoppApp/MoppApp/MyEid.storyboard
> Fix showing Forgot PIN buttons in My eID view
